import type { Metadata } from "next";
import { Inter } from "next/font/google";
import '../../../globals.css'
import Header from "./__component/header";
import { getUser } from "@/lib/auth";
import { redirect } from "next/navigation";


export const metadata: Metadata = {
  title: "Dashboard App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const {session} = await getUser()

  if(!session) {
    return redirect('/dashboard/login')
  }

  return (
    <html lang="en">
        <body>
            <div className="flex min-h-screen w-full flex-col">
                <Header/>
                <main className="flex flex-1 flex-col gap-4 p-4 md:gap-8 md:p-8">
                    {children}
                </main>
            </div>
        </body>
    </html>
);
}
